#!/usr/bin/env bash
# provision-futon-demo.sh — stand up an ISOLATED candidate FUTON installation
# for War Machine demos, following futon0/README-bare-metal.md (§3 closures,
# §2 toolchain assumptions, no credential copying).
#
# Isolation contract (enforced, not assumed):
#   * ordinary independent git clones (--no-local file:// => no shared object stores)
#   * own state root (XTDB store, roster, queue, token) under $DEMO_ROOT
#   * own port set (default 17070/17073/16768); refuses to provision if busy
#   * never writes outside $DEMO_ROOT; refuses $DEMO_ROOT under /home/joe
#   * no credentials copied; a fresh box-local admin token is generated instead
#   * starts nothing; --smoke only resolves deps and requires namespaces
#
# Parameters (env overrides):
#   DEMO_ROOT  target root          (default: ~/futon-demo)
#   SRC_BASE   source checkout base (default: /home/joe/code — read-only clone source)
#   DEMO_SITE  FUTON3C_SITE tag     (default: demo)
#   AGENCY_PORT / SUBSTRATE_PORT / DRAWBRIDGE_PORT  (default 17070 / 17073 / 16768)
#
# Usage:  bash provision-futon-demo.sh [--smoke]
set -euo pipefail

DEMO_ROOT="${DEMO_ROOT:-$HOME/futon-demo}"
SRC_BASE="${SRC_BASE:-/home/joe/code}"
DEMO_SITE="${DEMO_SITE:-demo}"
AGENCY_PORT="${AGENCY_PORT:-17070}"
SUBSTRATE_PORT="${SUBSTRATE_PORT:-17073}"
DRAWBRIDGE_PORT="${DRAWBRIDGE_PORT:-16768}"

# Classpath closure (README §3): futon3c :dev profile = these 13 roots, where
# futon1/apps/*, futon2/web/war-machine and futon4/dev/web/webarxana arrive as
# subdirectories of their parent-repo clones. The remaining repos are the
# first-class watcher roots (incomplete-model note in README §3).
REPOS=(futon3c futon3b futon1b futon0 futon2 futon3a futon5
       futon1 futon1a futon3 futon4 futon5a futon6 futon7 futon7a)

case "$DEMO_ROOT" in
  /home/joe/*|"$HOME"/../joe/*) echo "REFUSED: DEMO_ROOT must live outside /home/joe" >&2; exit 2;;
esac
[ -d "$SRC_BASE" ] || { echo "REFUSED: SRC_BASE $SRC_BASE missing" >&2; exit 2; }

for p in "$AGENCY_PORT" "$SUBSTRATE_PORT" "$DRAWBRIDGE_PORT"; do
  if ss -tln "sport = :$p" | grep -q LISTEN; then
    echo "REFUSED: port $p already listening; demo must not collide with live services" >&2; exit 3
  fi
done

mkdir -p "$DEMO_ROOT"/{code,state/futon1b,state/futon3c,systemd}

echo "==> cloning committed heads from $SRC_BASE (independent object stores)"
for r in "${REPOS[@]}"; do
  if [ ! -d "$DEMO_ROOT/code/$r/.git" ]; then
    git clone --quiet --no-local "file://$SRC_BASE/$r" "$DEMO_ROOT/code/$r"
  fi
  ( cd "$DEMO_ROOT/code/$r" && printf '%-9s %s\n' "$r" "$(git rev-parse --short HEAD)" )
done

echo "==> writing isolated environment (demo-env)"
cat > "$DEMO_ROOT/demo-env" <<ENV
# Generated by provision-futon-demo.sh — isolated demo profile. Source it.
export DEMO_ROOT="$DEMO_ROOT"
export FUTON3C_SITE="$DEMO_SITE"
export FUTON3C_ROLE=zone
export FUTON3C_SYSTEMD=1
export FUTON3C_BIND_HOST=127.0.0.1
export FUTON3C_PORT=$AGENCY_PORT
export FUTON3C_SELF_URL=http://127.0.0.1:$AGENCY_PORT
export FUTON3C_HEAP=4g
export FUTON3C_DIRECT=1g
export FUTON3C_IRC_PORT=0
export FUTON3C_RELAY_CLAUDE=false
export FUTON3C_RELAY_CODEX=false
export FUTON3C_REGISTER_CLAUDE=false
export FUTON3C_REGISTER_CLAUDE2=false
export FUTON3C_REGISTER_CODEX=false
export FUTON3C_BOOTSTRAP_AGENT_TYPES=
export FUTON3C_AGENT_ROSTER_FILE="$DEMO_ROOT/state/futon3c/demo-agent-roster.edn"
export FUTON3C_DURABLE_QUEUE_PATH="$DEMO_ROOT/state/futon3c/demo-turn-queue.edn"
export FUTON5_PORT=0
export FUTON1A_PORT=0
export FUTON3C_WEBARXANA_SERVER_AUTOSTART=false
export FUTON3C_SHADOW_AUTOSTART=false
export FUTON3C_EXTERNAL_HUD=0
export FUTON3C_DISPLAY_AGENTS_WINDOW=0
# Two-JVM standard: standalone substrate, isolated store, isolated port.
export FUTON1B_EMBED=0
export FUTON1B_PORT=$SUBSTRATE_PORT
export FUTON1B_BIND_HOST=127.0.0.1
export FUTON1B_STORE_DIR="$DEMO_ROOT/state/futon1b/demo-store"
export FUTON1B_URL=http://127.0.0.1:$SUBSTRATE_PORT
export FUTON_SUBSTRATE_URL=\$FUTON1B_URL
export FUTON1A_URL=\$FUTON_SUBSTRATE_URL
export FUTON4_BASE_URL=\$FUTON_SUBSTRATE_URL/api/alpha
export FUTON3C_DRAWBRIDGE_PORT=$DRAWBRIDGE_PORT
# No federation: this is a demo island.
export FUTON3C_PEERS=
export FUTON3C_PEER_SITES=
export FUTON3C_FED_SYNC_INTERVAL_MS=0
ENV

# Fresh box-local admin token; no credential is copied from any other account.
( umask 077
  head -c 32 /dev/urandom | base64 > "$DEMO_ROOT/.admintoken" )

echo "==> writing (not installing) systemd user unit template"
sed -e "s|%h/code/futon3c|$DEMO_ROOT/code/futon3c|g" \
    -e "s|Environment=FUTON3C_PORT=7070|Environment=FUTON3C_PORT=$AGENCY_PORT|" \
    -e "s|WorkingDirectory=.*|WorkingDirectory=$DEMO_ROOT/code/futon3c|" \
    "$DEMO_ROOT/code/futon3c/scripts/systemd/units/futon3c-zone.service" \
    > "$DEMO_ROOT/systemd/futon3c-demo.service"
echo "    (install manually as the owning user if/when desired; not enabled here)"

if [ "${1:-}" = "--smoke" ]; then
  echo "==> smoke: dependency resolution on the :dev-serve classpath (no server start)"
  ( cd "$DEMO_ROOT/code/futon3c" && clojure -M:dev-serve -P )
  echo "==> smoke: namespace loads without side channels"
  ( cd "$DEMO_ROOT/code/futon3c" && clojure -M:dev-serve -m clojure.main -e '
     (require (quote [futon3c.marks]))
     (require (quote [war-machine.server.core]))
     (println :demo-smoke-ok :namespaces-loadable)' )
  echo "==> smoke: bb orchestration deps"
  ( cd "$DEMO_ROOT/code/futon5" && bb -e "(+ 1 1)" >/dev/null && echo "bb ok" )
fi

echo "==> done. Root: $DEMO_ROOT"
echo "    Next (owner action, not automated): source demo-env, start substrate,"
echo "    then Agency; ports $AGENCY_PORT/$SUBSTRATE_PORT/$DRAWBRIDGE_PORT (loopback)."
